# Generated by Django 5.2.5 on 2025-10-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.URLField(),
        ),
    ]
