# Generated by Django 5.2.5 on 2025-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_images_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.URLField(max_length=5000),
        ),
    ]
